### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by sabas1080** [Lobaro/lora-packet-forwarder-client#1]
Hi @Niondir 
Do you have an example of how to use this?

Thanks

**Comment by niondir** [comment]
Start with `func NewClient(bind string, onNew func(Mac) error, onDelete func(Mac) error) (*Client, error)` from `client.go`

`bind` is some IP binding for the UDP socked, e.g. `:1234` to just bind to local port 1234.
`onNew` is called when a gateway gets connected to you endpoint
`onDelete` is called when a gateway ist removed somehow - not sure when exactly

Use the client channels: `client.RXPacketChan()`, `StatsChan()` to listen for packets received from packet-forwarders and `Send(txPacket TXPacketBytes)` to send something back.

On the gateway side you need to run a packet-forwarder that is configured in a way that is sends the packets to your open UDP socked of the client.

I hope this helps already. I would need a small test setup the provide some proper code example. Maybe you could come up with some concrete example?

**Comment by niondir** [comment]
I updated the readme and added some code in the example package. Hope that helps. If you have questions feel free to ask.
